/**
 * The exercise catalogue, in the order they are presented. Each one starts
 * from the fresh sample filesystem (see core/sample-fs.ts) plus its own
 * `setup`, and passes when `check` returns true after a command.
 *
 * To add an exercise: append an object with a new, unique id. The test suite
 * verifies that every `solution` really solves its task.
 */
import type { Challenge } from "./trainer";

const HOME = "/home/user";

/** Did the user run this command (as the first word, or anywhere in a pipeline)? */
const used = (argv: string[], name: string) => argv.includes(name);

/** Did the user pass a short flag letter, e.g. hasFlag(argv, "l") for `ls -la`? */
const hasFlag = (argv: string[], letter: string) => argv.some((a) => /^-[a-zA-Z]+$/.test(a) && a.includes(letter));

const navigation: Challenge[] = [
  {
    id: "nav-pwd",
    topic: "Navigation",
    title: "Where am I?",
    task: "Print the full path of the directory you are currently in.",
    hint: "The command name is short for 'print working directory'.",
    solution: ["pwd"],
    check: ({ shell, result }) => result.stdout === shell.cwd + "\n",
  },
  {
    id: "nav-ls",
    topic: "Navigation",
    title: "Look around",
    task: "List the files and folders in your home directory.",
    hint: "Two letters, short for 'list'.",
    solution: ["ls"],
    check: ({ argv, result }) => used(argv, "ls") && result.stdout.includes("documents"),
  },
  {
    id: "nav-cd",
    topic: "Navigation",
    title: "Step inside",
    task: "Move into the documents folder.",
    hint: "cd stands for 'change directory'. It takes the folder name as its argument.",
    solution: ["cd documents"],
    check: ({ shell }) => shell.cwd === `${HOME}/documents`,
  },
  {
    id: "nav-cd-up",
    topic: "Navigation",
    title: "Step back out",
    task: "You are inside documents. Go up one level to your home directory using the special name for the parent directory.",
    hint: "Every directory contains an entry called .. that means 'the directory above me'.",
    solution: ["cd .."],
    setup: (shell) => shell.changeDir("documents"),
    check: ({ shell, argv }) => shell.cwd === HOME && used(argv, ".."),
  },
  {
    id: "nav-ls-hidden",
    topic: "Navigation",
    title: "Hidden files",
    task: "Files whose names start with a dot are hidden. List your home directory so that hidden files are shown too.",
    hint: "ls has an option that shows 'all' entries.",
    solution: ["ls -a"],
    check: ({ argv, result }) => used(argv, "ls") && hasFlag(argv, "a") && result.stdout.includes(".bashrc"),
  },
  {
    id: "nav-ls-long",
    topic: "Navigation",
    title: "The long listing",
    task: "Show a detailed (long) listing of the documents folder, with permissions, sizes and dates.",
    hint: "ls -l gives the 'long' format. You can add a path after the option.",
    solution: ["ls -l documents"],
    check: ({ argv, result }) => used(argv, "ls") && hasFlag(argv, "l") && result.stdout.includes("essay.txt") && result.stdout.includes("rw-"),
  },
  {
    id: "nav-cd-abs",
    topic: "Navigation",
    title: "Absolute paths",
    task: "Go to the system log directory /var/log using its absolute path.",
    hint: "An absolute path starts with / and works from anywhere.",
    solution: ["cd /var/log"],
    check: ({ shell, argv }) => shell.cwd === "/var/log" && argv.some((a) => a.startsWith("/")),
  },
  {
    id: "nav-cd-home",
    topic: "Navigation",
    title: "Straight home",
    task: "You are in /var/log. Jump straight back to your home directory with the shortest possible command.",
    hint: "cd with no argument goes home. So does cd ~.",
    solution: ["cd"],
    setup: (shell) => shell.changeDir("/var/log"),
    check: ({ shell, line }) => shell.cwd === HOME && /^cd( ~)?$/.test(line.trim()),
  },
  {
    id: "nav-cd-dash",
    topic: "Navigation",
    title: "Bounce back",
    task: "Go to /tmp, then return to the directory you came from using cd's 'previous directory' shortcut.",
    hint: "cd - takes you to wherever you were before the last cd.",
    solution: ["cd /tmp", "cd -"],
    check: ({ shell, line }) => line.trim() === "cd -" && shell.oldCwd === "/tmp",
  },
  {
    id: "nav-tree",
    topic: "Navigation",
    title: "The big picture",
    task: "Show the whole structure of the projects folder as a tree.",
    hint: "There is a command literally called tree.",
    solution: ["tree projects"],
    check: ({ argv, result }) => used(argv, "tree") && result.stdout.includes("website") && result.stdout.includes("hello.py"),
  },
];

const files: Challenge[] = [
  {
    id: "files-touch",
    topic: "Files",
    title: "An empty file",
    task: "Create an empty file called hello.txt in your home directory.",
    hint: "touch creates a file if it does not exist yet.",
    solution: ["touch hello.txt"],
    check: ({ shell }) => shell.fs.isFile(`${HOME}/hello.txt`),
  },
  {
    id: "files-mkdir",
    topic: "Files",
    title: "A new folder",
    task: "Create a directory named workspace in your home directory.",
    hint: "mkdir is short for 'make directory'.",
    solution: ["mkdir workspace"],
    check: ({ shell }) => shell.fs.isDir(`${HOME}/workspace`),
  },
  {
    id: "files-mkdir-p",
    topic: "Files",
    title: "Nested folders in one go",
    task: "Create the folders projects/api/src (api does not exist yet) with a single command.",
    hint: "mkdir has an option that creates missing 'parent' directories.",
    solution: ["mkdir -p projects/api/src"],
    check: ({ shell, argv }) => shell.fs.isDir(`${HOME}/projects/api/src`) && hasFlag(argv, "p"),
  },
  {
    id: "files-cp",
    topic: "Files",
    title: "Copy a file",
    task: "Make a copy of notes.txt called notes-backup.txt.",
    hint: "cp SOURCE DESTINATION",
    solution: ["cp notes.txt notes-backup.txt"],
    check: ({ shell }) =>
      shell.fs.isFile(`${HOME}/notes-backup.txt`) && shell.fs.readFile(`${HOME}/notes-backup.txt`) === shell.fs.readFile(`${HOME}/notes.txt`),
  },
  {
    id: "files-cp-dir",
    topic: "Files",
    title: "Copy a folder",
    task: "Copy the entire documents folder to a new folder called docs-copy.",
    hint: "Copying a directory needs the 'recursive' option: cp -r",
    solution: ["cp -r documents docs-copy"],
    check: ({ shell }) => shell.fs.isFile(`${HOME}/docs-copy/essay.txt`) && shell.fs.isDir(`${HOME}/documents`),
  },
  {
    id: "files-mv-rename",
    topic: "Files",
    title: "Rename",
    task: "Rename todo.txt to tasks.txt.",
    hint: "There is no rename command; moving a file to a new name does the job.",
    solution: ["mv todo.txt tasks.txt"],
    check: ({ shell }) => !shell.fs.exists(`${HOME}/todo.txt`) && shell.fs.readFile(`${HOME}/tasks.txt`).includes("pay rent"),
  },
  {
    id: "files-mv-into",
    topic: "Files",
    title: "Move into a folder",
    task: "Move the file data/scores.txt into the documents folder.",
    hint: "When the destination is a directory, mv puts the file inside it.",
    solution: ["mv data/scores.txt documents"],
    check: ({ shell }) => shell.fs.isFile(`${HOME}/documents/scores.txt`) && !shell.fs.exists(`${HOME}/data/scores.txt`),
  },
  {
    id: "files-rm",
    topic: "Files",
    title: "Delete a file",
    task: "Delete the file downloads/invoice.pdf.",
    hint: "rm removes files. There is no undo, so look before you type.",
    solution: ["rm downloads/invoice.pdf"],
    check: ({ shell }) => !shell.fs.exists(`${HOME}/downloads/invoice.pdf`) && shell.fs.isDir(`${HOME}/downloads`),
  },
  {
    id: "files-rmdir",
    topic: "Files",
    title: "Delete an empty folder",
    task: "Remove the empty pictures directory using the command meant for empty directories.",
    hint: "rmdir only works on empty directories, which makes it a safe choice.",
    solution: ["rmdir pictures"],
    check: ({ shell, argv }) => !shell.fs.exists(`${HOME}/pictures`) && used(argv, "rmdir"),
  },
  {
    id: "files-rm-r",
    topic: "Files",
    title: "Delete a folder and its contents",
    task: "Delete the downloads folder together with everything inside it.",
    hint: "rm needs -r (recursive) to remove a directory tree.",
    solution: ["rm -r downloads"],
    check: ({ shell, argv }) => !shell.fs.exists(`${HOME}/downloads`) && used(argv, "rm"),
  },
  {
    id: "files-glob-mv",
    topic: "Files",
    title: "Wildcards",
    task: "Move every .sh file from projects/scripts into the backup folder with one command, using a wildcard.",
    hint: "*.sh matches every name ending in .sh. The shell expands it before mv runs.",
    solution: ["mv projects/scripts/*.sh backup"],
    check: ({ shell, line }) =>
      line.includes("*") &&
      shell.fs.isFile(`${HOME}/backup/backup.sh`) &&
      shell.fs.isFile(`${HOME}/backup/deploy.sh`) &&
      !shell.fs.exists(`${HOME}/projects/scripts/backup.sh`) &&
      shell.fs.isFile(`${HOME}/projects/scripts/hello.py`),
  },
  {
    id: "files-echo-create",
    topic: "Files",
    title: "Write a file",
    task: "Create a file called greeting.txt containing the text: hello world",
    hint: "echo prints text; the > operator sends that output into a file instead of the screen.",
    solution: ["echo hello world > greeting.txt"],
    check: ({ shell }) => shell.fs.isFile(`${HOME}/greeting.txt`) && shell.fs.readFile(`${HOME}/greeting.txt`).trim() === "hello world",
  },
];

const viewing: Challenge[] = [
  {
    id: "view-cat",
    topic: "Viewing",
    title: "Read a file",
    task: "Print the contents of notes.txt.",
    hint: "cat prints a file to the screen.",
    solution: ["cat notes.txt"],
    check: ({ shell, result }) => result.stdout === shell.fs.readFile(`${HOME}/notes.txt`),
  },
  {
    id: "view-head",
    topic: "Viewing",
    title: "Just the beginning",
    task: "Show only the first 3 lines of logs/app.log.",
    hint: "head shows the start of a file; -n sets how many lines.",
    solution: ["head -n 3 logs/app.log"],
    check: ({ shell, result }) => result.stdout === shell.fs.readFile(`${HOME}/logs/app.log`).split("\n").slice(0, 3).join("\n") + "\n",
  },
  {
    id: "view-tail",
    topic: "Viewing",
    title: "Just the end",
    task: "Show only the last 2 lines of logs/app.log.",
    hint: "tail is the opposite of head.",
    solution: ["tail -n 2 logs/app.log"],
    check: ({ shell, result }) => result.stdout === shell.fs.readFile(`${HOME}/logs/app.log`).trim().split("\n").slice(-2).join("\n") + "\n",
  },
  {
    id: "view-wc",
    topic: "Viewing",
    title: "How long is it?",
    task: "Count how many lines data/people.csv has.",
    hint: "wc counts things; -l limits it to lines.",
    solution: ["wc -l data/people.csv"],
    check: ({ argv, result }) => used(argv, "wc") && /^\s*7\b/.test(result.stdout),
  },
  {
    id: "view-cat-n",
    topic: "Viewing",
    title: "Numbered lines",
    task: "Print documents/essay.txt with a number in front of every line.",
    hint: "cat has an option for numbering.",
    solution: ["cat -n documents/essay.txt"],
    check: ({ argv, result }) => used(argv, "cat") && /^\s+1\t/.test(result.stdout) && result.stdout.includes("Unix philosophy"),
  },
  {
    id: "view-man",
    topic: "Viewing",
    title: "Read the manual",
    task: "Open the manual page for the ls command.",
    hint: "man COMMAND shows the manual for COMMAND.",
    solution: ["man ls"],
    check: ({ argv }) => argv[0] === "man" && argv[1] === "ls",
  },
];

const searching: Challenge[] = [
  {
    id: "search-grep",
    topic: "Searching",
    title: "Find the errors",
    task: "Print every line of logs/app.log that contains the word ERROR.",
    hint: "grep PATTERN FILE prints matching lines.",
    solution: ["grep ERROR logs/app.log"],
    check: ({ shell, result }) =>
      result.stdout === shell.fs.readFile(`${HOME}/logs/app.log`).split("\n").filter((l) => l.includes("ERROR")).join("\n") + "\n",
  },
  {
    id: "search-grep-i",
    topic: "Searching",
    title: "Ignore case",
    task: "Find the line in notes.txt that mentions 'call', whether it is written Call or call.",
    hint: "grep -i ignores upper/lower case.",
    solution: ["grep -i call notes.txt"],
    check: ({ argv, result }) => used(argv, "grep") && hasFlag(argv, "i") && result.stdout === "Call the dentist on Tuesday\n",
  },
  {
    id: "search-grep-c",
    topic: "Searching",
    title: "Count matches",
    task: "How many lines in logs/app.log contain WARN? Print just the number.",
    hint: "grep -c counts matching lines instead of printing them (grep ... | wc -l works too).",
    solution: ["grep -c WARN logs/app.log"],
    check: ({ argv, result }) => used(argv, "grep") && result.stdout.trim() === "2",
  },
  {
    id: "search-grep-n",
    topic: "Searching",
    title: "Which line?",
    task: "Find the line in logs/app.log containing 'Retrying' and show its line number next to it.",
    hint: "grep -n prefixes each match with its line number.",
    solution: ["grep -n Retrying logs/app.log"],
    check: ({ result }) => result.stdout.startsWith("5:"),
  },
  {
    id: "search-grep-r",
    topic: "Searching",
    title: "Search a whole folder",
    task: "Search every file under the projects folder for the word TODO.",
    hint: "grep -r searches directories recursively.",
    solution: ["grep -r TODO projects"],
    check: ({ argv, result }) => used(argv, "grep") && result.stdout.includes("app.js") && result.stdout.includes("backup.sh"),
  },
  {
    id: "search-find-name",
    topic: "Searching",
    title: "Find by name",
    task: "Find every file ending in .sh anywhere under your home directory.",
    hint: "find PATH -name 'PATTERN'. Quote the pattern so the shell does not expand it first.",
    solution: ["find . -name '*.sh'"],
    check: ({ argv, result }) => used(argv, "find") && ["setup.sh", "backup.sh", "deploy.sh"].every((f) => result.stdout.includes(f)),
  },
  {
    id: "search-find-type",
    topic: "Searching",
    title: "Find only folders",
    task: "List every directory (not files) inside the projects folder using find.",
    hint: "find has a -type test: d for directories, f for files.",
    solution: ["find projects -type d"],
    check: ({ argv, result }) =>
      used(argv, "find") && result.stdout.includes("projects/website") && result.stdout.includes("projects/scripts") && !result.stdout.includes("hello.py"),
  },
  {
    id: "search-find-etc",
    topic: "Searching",
    title: "Search the system",
    task: "Find the file named hostname somewhere under /etc.",
    hint: "find /etc -name hostname",
    solution: ["find /etc -name hostname"],
    check: ({ argv, result }) => used(argv, "find") && result.stdout.trim() === "/etc/hostname",
  },
];

const pipes: Challenge[] = [
  {
    id: "pipe-sort-n",
    topic: "Pipes",
    title: "Sort numbers",
    task: "Print data/scores.txt sorted from smallest to largest number.",
    hint: "Plain sort orders text (10 before 9). Use -n for numeric order.",
    solution: ["sort -n data/scores.txt"],
    check: ({ result }) => result.stdout === "8\n17\n25\n42\n63\n99\n99\n",
  },
  {
    id: "pipe-uniq",
    topic: "Pipes",
    title: "Unique words",
    task: "Print each distinct word in data/words.txt exactly once, in alphabetical order.",
    hint: "uniq only removes neighbouring duplicates, so sort first and pipe the result into uniq.",
    solution: ["sort data/words.txt | uniq"],
    check: ({ result }) => result.stdout === "apple\nbanana\ncherry\ndate\n",
  },
  {
    id: "pipe-uniq-c",
    topic: "Pipes",
    title: "Count occurrences",
    task: "Show how many times each word appears in data/words.txt.",
    hint: "sort | uniq -c",
    solution: ["sort data/words.txt | uniq -c"],
    check: ({ result }) => /3 apple/.test(result.stdout) && /2 banana/.test(result.stdout) && /1 cherry/.test(result.stdout),
  },
  {
    id: "pipe-ls-wc",
    topic: "Pipes",
    title: "Count entries",
    task: "Use a pipe to count how many entries ls shows in your home directory.",
    hint: "The output of ls can be piped into wc -l.",
    solution: ["ls | wc -l"],
    check: ({ shell, line, argv, result }) => {
      const visible = shell.fs.readdir(HOME).filter((n) => !n.startsWith(".")).length;
      return line.includes("|") && used(argv, "wc") && result.stdout.trim() === String(visible);
    },
  },
  {
    id: "pipe-top-scores",
    topic: "Pipes",
    title: "Top three",
    task: "Print the three highest numbers in data/scores.txt.",
    hint: "Sort numerically, then keep only the last three lines.",
    solution: ["sort -n data/scores.txt | tail -n 3"],
    check: ({ result }) => result.stdout === "63\n99\n99\n" || result.stdout === "99\n99\n63\n",
  },
  {
    id: "pipe-grep-wc",
    topic: "Pipes",
    title: "Count requests",
    task: "Count how many GET requests appear in logs/access.log.",
    hint: "grep for GET, then count the lines (or use grep -c).",
    solution: ["grep GET logs/access.log | wc -l"],
    check: ({ argv, result }) => used(argv, "grep") && result.stdout.trim() === "4",
  },
  {
    id: "pipe-cut",
    topic: "Pipes",
    title: "One column",
    task: "Print only the name column (the first field) of data/people.csv.",
    hint: "cut -d , -f 1 splits on commas and keeps field 1.",
    solution: ["cut -d , -f 1 data/people.csv"],
    check: ({ result }) => result.stdout.includes("Alice\nBob\nCarla\nDmitri\nEve\nFarid\n") && !result.stdout.includes("London"),
  },
  {
    id: "pipe-awk",
    topic: "Pipes",
    title: "Third column",
    task: "Print only the city (third field) of every person in data/people.csv, using awk.",
    hint: "awk -F, '{print $3}' FILE",
    solution: ["awk -F, '{print $3}' data/people.csv"],
    check: ({ argv, result }) => used(argv, "awk") && result.stdout.includes("London\nParis\nMadrid\nBerlin\nLondon\nCairo\n"),
  },
  {
    id: "pipe-tr",
    topic: "Pipes",
    title: "SHOUT",
    task: "Print notes.txt in UPPERCASE.",
    hint: "tr a-z A-Z translates lowercase to uppercase. Feed the file in with cat and a pipe, or with <.",
    solution: ["cat notes.txt | tr a-z A-Z"],
    check: ({ shell, result }) => result.stdout === shell.fs.readFile(`${HOME}/notes.txt`).toUpperCase(),
  },
  {
    id: "pipe-sed",
    topic: "Pipes",
    title: "Find and replace",
    task: "Print notes.txt with every 'bread' replaced by 'cake'. Do not change the file itself.",
    hint: "sed 's/old/new/g' FILE  (the g means every occurrence, not just the first per line)",
    solution: ["sed 's/bread/cake/g' notes.txt"],
    check: ({ shell, result }) =>
      result.stdout === shell.fs.readFile(`${HOME}/notes.txt`).replaceAll("bread", "cake") && shell.fs.readFile(`${HOME}/notes.txt`).includes("bread"),
  },
  {
    id: "pipe-sed-i",
    topic: "Pipes",
    title: "Edit in place",
    task: "In the hidden file .bashrc, change the editor from nano to vim by editing the file in place.",
    hint: "sed -i edits the file instead of printing.",
    solution: ["sed -i 's/nano/vim/' .bashrc"],
    check: ({ shell }) => shell.fs.readFile(`${HOME}/.bashrc`).includes("EDITOR=vim"),
  },
  {
    id: "pipe-redirect",
    topic: "Pipes",
    title: "Save output to a file",
    task: "Save the long listing of your home directory (ls -l) into a file called listing.txt.",
    hint: "The > operator redirects output into a file, creating or overwriting it.",
    solution: ["ls -l > listing.txt"],
    check: ({ shell }) => shell.fs.isFile(`${HOME}/listing.txt`) && shell.fs.readFile(`${HOME}/listing.txt`).includes("documents"),
  },
  {
    id: "pipe-append",
    topic: "Pipes",
    title: "Append, don't overwrite",
    task: "Add the line 'buy coffee' to the end of notes.txt without losing what is already there.",
    hint: ">> appends; a single > would wipe the file first.",
    solution: ["echo buy coffee >> notes.txt"],
    check: ({ shell }) => {
      const text = shell.fs.readFile(`${HOME}/notes.txt`);
      return text.startsWith("Shopping: milk") && text.endsWith("buy coffee\n");
    },
  },
  {
    id: "pipe-stdin",
    topic: "Pipes",
    title: "Input redirection",
    task: "Sort data/words.txt by giving sort the file through input redirection (<) rather than as an argument.",
    hint: "sort < FILE",
    solution: ["sort < data/words.txt"],
    check: ({ line, result }) => line.includes("<") && result.stdout === "apple\napple\napple\nbanana\nbanana\ncherry\ndate\n",
  },
  {
    id: "pipe-xargs",
    topic: "Pipes",
    title: "find + xargs",
    task: "Delete every .log file under the logs folder using find and xargs together.",
    hint: "find logs -name '*.log' | xargs rm",
    solution: ["find logs -name '*.log' | xargs rm"],
    check: ({ shell, argv }) => used(argv, "xargs") && !shell.fs.exists(`${HOME}/logs/app.log`) && !shell.fs.exists(`${HOME}/logs/access.log`),
  },
  {
    id: "pipe-chain",
    topic: "Pipes",
    title: "Only if it worked",
    task: "In one line: create a folder called release and, only if that succeeds, create the empty file release/notes.txt inside it.",
    hint: "cmd1 && cmd2 runs cmd2 only when cmd1 succeeds.",
    solution: ["mkdir release && touch release/notes.txt"],
    check: ({ shell, line }) => line.includes("&&") && shell.fs.isFile(`${HOME}/release/notes.txt`),
  },
];

const system: Challenge[] = [
  {
    id: "perm-chmod-x",
    topic: "Permissions",
    title: "Make it executable",
    task: "Give projects/scripts/deploy.sh execute permission.",
    hint: "chmod +x FILE adds the execute bit.",
    solution: ["chmod +x projects/scripts/deploy.sh"],
    check: ({ shell }) => (shell.fs.stat(`${HOME}/projects/scripts/deploy.sh`)!.mode & 0o111) !== 0,
  },
  {
    id: "perm-chmod-num",
    topic: "Permissions",
    title: "Numeric modes",
    task: "Set the permissions of downloads/setup.sh to rwxr-xr-x using the numeric form.",
    hint: "r=4, w=2, x=1. Add them up per group: owner, group, others.",
    solution: ["chmod 755 downloads/setup.sh"],
    check: ({ shell, argv }) => shell.fs.stat(`${HOME}/downloads/setup.sh`)!.mode === 0o755 && used(argv, "755"),
  },
  {
    id: "perm-chmod-sym",
    topic: "Permissions",
    title: "Lock it down",
    task: "notes.txt is currently writable by everyone (rw-rw-rw-). Remove write permission from group and others, leaving the owner's permissions alone.",
    hint: "chmod go-w FILE  (g = group, o = others, - = remove, w = write)",
    solution: ["chmod go-w notes.txt"],
    setup: (shell) => shell.fs.chmod(`${HOME}/notes.txt`, 0o666),
    check: ({ shell }) => {
      const mode = shell.fs.stat(`${HOME}/notes.txt`)!.mode;
      return (mode & 0o022) === 0 && (mode & 0o600) === 0o600;
    },
  },
  {
    id: "perm-ls-l",
    topic: "Permissions",
    title: "Check permissions",
    task: "Show the permissions of the files in projects/scripts with a long listing.",
    hint: "ls -l shows a permission string like -rwxr-xr-x for each entry.",
    solution: ["ls -l projects/scripts"],
    check: ({ argv, result }) => used(argv, "ls") && hasFlag(argv, "l") && result.stdout.includes("deploy.sh"),
  },
  {
    id: "env-echo-home",
    topic: "Environment",
    title: "Variables",
    task: "Print the value of the HOME environment variable.",
    hint: "Put a $ in front of a variable's name to use its value: echo $HOME",
    solution: ["echo $HOME"],
    check: ({ line, result }) => line.includes("$HOME") && result.stdout === `${HOME}\n`,
  },
  {
    id: "env-export",
    topic: "Environment",
    title: "Set a variable",
    task: "Create an environment variable named EDITOR with the value vim, then print it.",
    hint: "export NAME=value, then echo $NAME",
    solution: ["export EDITOR=vim", "echo $EDITOR"],
    check: ({ shell, result }) => shell.env.get("EDITOR") === "vim" && result.stdout === "vim\n",
  },
  {
    id: "env-whoami",
    topic: "Environment",
    title: "Who am I?",
    task: "Print the name of the user you are logged in as.",
    hint: "The command is literally the question.",
    solution: ["whoami"],
    check: ({ argv, result }) => used(argv, "whoami") && result.stdout === "user\n",
  },
  {
    id: "env-history",
    topic: "Environment",
    title: "What did I type?",
    task: "Show the list of commands you have run so far.",
    hint: "history",
    solution: ["history"],
    check: ({ argv }) => argv[0] === "history",
  },
  {
    id: "env-exit-code",
    topic: "Environment",
    title: "Exit codes",
    task: "Run a command that fails (for example cat on a file that does not exist), then print the exit code of that command.",
    hint: "$? holds the exit code of the last command. Print it with echo.",
    solution: ["cat nothing.txt", "echo $?"],
    check: ({ line, result }) => line.includes("$?") && result.stdout.trim() === "1",
  },
  {
    id: "env-passwd",
    topic: "Environment",
    title: "Put it all together",
    task: "Print only the usernames (first field) from /etc/passwd, sorted alphabetically.",
    hint: "cut -d : -f 1 /etc/passwd | sort",
    solution: ["cut -d : -f 1 /etc/passwd | sort"],
    check: ({ result }) => result.stdout === "daemon\nroot\nuser\nwww-data\n",
  },
];

export const challenges: Challenge[] = [...navigation, ...files, ...viewing, ...searching, ...pipes, ...system];
